C2 complete
Ehotuwe/Py111-praktika1 pull request #12
Opened 2021-01-12 21:34 UTC by Ehotuwe

2021-01-13 05:36 UTC, EnotYoyo requested changes
Для входа binary_search(2, [1, 2, 2, 2, 2]) выдает 2, а должен 1.

2021-01-21 16:10 UTC, Ehotuwe commented
Изменил код @EnotYoyo

2021-01-22 10:55 UTC, EnotYoyo commented on Tasks/c2_recursive_binary_search.py
> +            return binary_search (elem, arr[:mid_ind + 1])
Я в целом принимаю задание со срезами, но взятие среза - очень дорогая операция. Вы должны были добавить два параметра в функцию - левая и правая граница и использовать только индексы в первоначальном массиве.

2021-01-22 10:55 UTC, EnotYoyo requested changes
Не работает для binary_search(2, [2, 2, 2, 2]) (должен возвращаться 0).

2021-01-23 09:32 UTC, merged